### ISSUE TITLE
login and use on mobiles

### ISSUE THREAD

**Issue by dobefore** [XPoet/picx#304]
hi.how can I login onto the website and use it on mobile devices?

I find it not accessible using whether github token or Oauth method.therefore it's not available on the phone to use its service.

**Comment by cnbilinyj** [comment]
> hi.how can I login onto the website and use it on mobile devices?
> 
> I find it not accessible using whether github token or Oauth method.therefore it's not available on the phone to use its service.


https://github.com/XPoet/picx/assets/99505726/9ee74069-e4e7-43ae-a16a-87aa5e7de549

**Comment by XPoet** [comment]
PicX is also available on mobile

**Comment by dobefore** [comment]
@cnbilinyj thanks for the video.the key is to change the language to English.

**Comment by cnbilinyj** [comment]
No, I'm afraid you won't understand.
In view of the fact that the language you used to send the issue is English, I don't think you are from China by default. Therefore, the interface language was specially changed to English when recording the screen.

于 2024年6月5日 GMT+08:00 上午11:23:28，Grape Pu ***@***.***> 写道：
>@cnbilinyj thanks for the video.the key is to change the language to English.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/XPoet/picx/issues/304#issuecomment-2148781917
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
农药君
***@***.***

**Comment by dobefore** [comment]
@cnbilinyj sorry,I misunderstood your intention.it works on mobile whatever the interfere language is.
and thanks for your reply.
